version: "3.8"

services:
  csv-ingestion:
    build: .
    container_name: csv-ingestion-app
    stdin_open: true
    tty: true
    env_file: .env
    volumes:
      - .:/app
      - /tmp:/tmp
    working_dir: /app
    command: tail -f /dev/null
