import shutil
import tempfile
from pathlib import Path

from app.models.project import DbtRepo
from app.services.dbt_scaffold_versions_service import scaffold_source_dir
from app.services.github_service import GitHubService, GitHubError


class DbtScaffoldError(Exception):
    pass


async def scaffold_dbt_repo(repo: DbtRepo) -> str | None:
    """Vendors dbt/scaffold/<stack>/<repo.scaffold_version>/ into the
    connected dbt repo via a PR — same versioned-folder-copy pattern as the
    Terraform modules (see module source_dir / _copy_modules). Idempotent:
    skips (returns None) if the repo already has a Makefile, since that's
    the clearest sign scaffolding already happened and nothing here should
    silently overwrite hand-edited project files."""
    base_path = "" if repo.dbt_base_path in (".", "") else repo.dbt_base_path.strip("/")
    svc = GitHubService(
        token=repo.token,
        repo_full_name=repo.repo_full_name,
        branch=repo.branch,
        api_url=repo.api_url,
        base_path=base_path,
    )

    existing_makefile = await svc.get_file_content("Makefile", ref=repo.branch)
    if existing_makefile is not None:
        return None

    version_dir = scaffold_source_dir(repo.scaffold_version)
    if not version_dir.exists():
        raise DbtScaffoldError(f"No dbt scaffold found for version '{repo.scaffold_version}'")

    with tempfile.TemporaryDirectory() as staging:
        staging_path = Path(staging)
        shutil.copytree(version_dir, staging_path, dirs_exist_ok=True)

        try:
            pr_url, _ = await svc.open_pull_request(
                local_dir=staging_path,
                feature_branch=f"chore/dbt-scaffold-{repo.scaffold_version}",
                commit_message=f"chore(dbt): scaffold project structure ({repo.scaffold_version})",
                pr_title="chore(dbt): scaffold project structure",
                pr_body=(
                    "## Summary\n\n"
                    f"Vendors the baseline dbt project structure (version `{repo.scaffold_version}`):\n\n"
                    "- `dbt_project.yml` + `profiles.yml` (connection config from env vars — no "
                    "secrets committed)\n"
                    "- `models/` and `macros/`\n"
                    "- `docker/Dockerfile` — pinned dbt-snowflake image\n"
                    "- `Makefile` — `predeploy`/`deploy`/`postdeploy` targets, callable from any CI "
                    "system\n\n"
                    "Not auto-merged — review before merging, same as every dbt PR Canary opens.\n\n"
                    "---\n🤖 Generated by Canary"
                ),
            )
        except GitHubError as exc:
            raise DbtScaffoldError(str(exc)) from exc

    return pr_url
