import os
import shutil
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from app.models.project import GitHubRepo
from app.models.stack import Stack
from app.services.git_ops import clone_repo, has_changes, commit_and_push, GitOpsError
from app.services.github_service import GitHubService, GitHubError
from app.services.module_versions_service import MODULE_COMPONENTS, module_source_dir


@dataclass
class ModuleRefreshResult:
    pr_url: str | None
    files_removed: int
    files_added: int


class ModuleRefreshError(Exception):
    pass


async def hard_refresh_modules(repo: GitHubRepo, stack: Stack) -> ModuleRefreshResult:
    """Wipe every vendored file under this stack's `modules/` directory and
    re-copy them fresh from the stack's pinned module_version, opening a PR
    with both the deletions and the additions. Returns pr_url=None if the
    stack's modules/ already matches that version exactly (nothing to push)."""
    clone_dir = None
    try:
        try:
            clone_dir = clone_repo(repo.token, repo.repo_full_name, stack.branch)
        except GitOpsError as exc:
            raise ModuleRefreshError(str(exc)) from exc

        base_path = repo.infrastructure_base_path.strip("/")
        base = (Path(clone_dir) / base_path) if base_path else Path(clone_dir)
        modules_dir = base / "modules"

        removed_count = sum(1 for p in modules_dir.rglob("*") if p.is_file()) if modules_dir.exists() else 0
        if modules_dir.exists():
            shutil.rmtree(modules_dir)

        added_count = 0
        for rel_path in MODULE_COMPONENTS:
            src = module_source_dir(stack.module_version) / rel_path
            if not src.exists():
                continue
            dst = modules_dir / rel_path
            os.makedirs(dst.parent, exist_ok=True)
            shutil.copytree(src, dst, dirs_exist_ok=True)
            added_count += sum(1 for p in dst.rglob("*") if p.is_file())

        if not has_changes(clone_dir):
            return ModuleRefreshResult(pr_url=None, files_removed=0, files_added=0)

        slug = datetime.now().strftime("%Y%m%d-%H%M%S")
        feature_branch = f"chore/modules-hard-refresh-{stack.name}-{slug}"
        try:
            commit_and_push(
                clone_dir, feature_branch,
                f"chore(modules): hard refresh to {stack.module_version} ({stack.name})",
            )
        except GitOpsError as exc:
            raise ModuleRefreshError(str(exc)) from exc

        svc = GitHubService(
            token=repo.token,
            repo_full_name=repo.repo_full_name,
            branch=stack.branch,
            api_url=repo.api_url,
        )
        try:
            pr_url = await svc.open_branch_pr(
                head=feature_branch,
                base=stack.branch,
                title=f"chore(modules): hard refresh to {stack.module_version} ({stack.name})",
                body=(
                    f"## Summary\n\n"
                    f"Removes every vendored file under `modules/` on the `{stack.name}` stack and "
                    f"re-copies them fresh from module version `{stack.module_version}`. Use this after "
                    f"bumping a stack's pinned module version to make sure no stale files from an older "
                    f"version are left behind.\n\n"
                    f"- Files removed: {removed_count}\n"
                    f"- Files added: {added_count}\n\n"
                    f"---\n🤖 Generated by Canary"
                ),
            )
        except GitHubError as exc:
            raise ModuleRefreshError(str(exc)) from exc

        return ModuleRefreshResult(pr_url=pr_url, files_removed=removed_count, files_added=added_count)
    finally:
        if clone_dir:
            shutil.rmtree(clone_dir, ignore_errors=True)
