"""Release flow: promotes a stack's branch into prod (main) and/or dev (develop).

- Releasing to prod: creates a new branch off prod's tip, merges the source
  stack's branch into it — favoring prod's side on any conflicting lines, per
  policy, with a commit message documenting what happened — then opens two
  PRs from that one branch: one to prod, one to dev (keeps dev in sync with
  what's shipping to prod).
- Releasing to dev only (a non-dev/non-prod stack choosing "develop" as its
  target): a direct PR from the source branch to dev's branch, no merge needed
  since prod isn't involved.

The "dev" stack can only release to prod (there's nothing upstream of it but
prod). The "prod" stack can't release at all — it's already production.
"""
import shutil
import subprocess
import tempfile
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from app.models.project import GitHubRepo
from app.models.stack import Stack
from app.services.github_service import GitHubService, GitHubError

GIT_AUTHOR_NAME = "Canary"
GIT_AUTHOR_EMAIL = "canary@pensievetechnologies.com"


class ReleaseError(Exception):
    pass


@dataclass
class ReleaseResult:
    pr_urls: list[str]
    branch: str | None = None


async def _get_repo(db: AsyncSession, account_id: str) -> GitHubRepo:
    result = await db.execute(select(GitHubRepo).where(GitHubRepo.account_id == account_id))
    repo = result.scalar_one_or_none()
    if not repo:
        raise ReleaseError("No GitHub repo connected. Use POST /api/v1/github/repos first.")
    return repo


async def _get_stack(db: AsyncSession, account_id: str, name: str) -> Stack:
    result = await db.execute(select(Stack).where(Stack.account_id == account_id, Stack.name == name))
    stack = result.scalar_one_or_none()
    if not stack:
        raise ReleaseError(f"No '{name}' stack found for this account.")
    return stack


def _run(args: list[str], cwd: Path) -> subprocess.CompletedProcess:
    return subprocess.run(args, cwd=cwd, capture_output=True, text=True)


def _clone(repo: GitHubRepo, clone_dir: Path) -> None:
    clone_url = f"https://{repo.token}@github.com/{repo.repo_full_name}.git"
    result = subprocess.run(["git", "clone", clone_url, str(clone_dir)], capture_output=True, text=True)
    if result.returncode != 0:
        raise ReleaseError(f"Failed to clone {repo.repo_full_name}: {result.stderr}")
    _run(["git", "config", "user.email", GIT_AUTHOR_EMAIL], clone_dir)
    _run(["git", "config", "user.name", GIT_AUTHOR_NAME], clone_dir)


async def release_stack(
    db: AsyncSession,
    account_id: str,
    source_stack_name: str,
    target: str,
) -> ReleaseResult:
    if target not in ("prod", "develop"):
        raise ReleaseError("target must be 'prod' or 'develop'")
    if source_stack_name == "prod":
        raise ReleaseError("The 'prod' stack cannot be released — it's already production.")
    if source_stack_name == "dev" and target != "prod":
        raise ReleaseError("The 'dev' stack can only release to prod.")

    repo = await _get_repo(db, account_id)
    source_stack = await _get_stack(db, account_id, source_stack_name)
    prod_stack = await _get_stack(db, account_id, "prod")
    dev_stack = await _get_stack(db, account_id, "dev")

    if target == "develop":
        return await _release_to_dev(repo, source_stack, dev_stack)
    return await _release_to_prod(repo, source_stack, prod_stack, dev_stack)


async def _release_to_dev(repo: GitHubRepo, source_stack: Stack, dev_stack: Stack) -> ReleaseResult:
    svc = GitHubService(token=repo.token, repo_full_name=repo.repo_full_name, branch=dev_stack.branch, api_url=repo.api_url)
    try:
        pr_url = await svc.open_branch_pr(
            head=source_stack.branch,
            base=dev_stack.branch,
            title=f"release: {source_stack.name} → {dev_stack.name}",
            body=(
                f"## Release\n\n"
                f"Promotes `{source_stack.branch}` (**{source_stack.name}**) into "
                f"`{dev_stack.branch}` (**{dev_stack.name}**).\n\n"
                f"---\n🤖 Generated by Canary"
            ),
        )
    except GitHubError as exc:
        raise ReleaseError(str(exc))
    return ReleaseResult(pr_urls=[pr_url])


async def _release_to_prod(
    repo: GitHubRepo, source_stack: Stack, prod_stack: Stack, dev_stack: Stack
) -> ReleaseResult:
    clone_dir = Path(tempfile.mkdtemp(prefix="release-"))
    try:
        _clone(repo, clone_dir)

        slug = datetime.now().strftime("%Y%m%d-%H%M%S")
        release_branch = f"release/{source_stack.name}-to-{prod_stack.name}-{slug}"

        r = _run(["git", "checkout", "-b", release_branch, f"origin/{prod_stack.branch}"], clone_dir)
        if r.returncode != 0:
            raise ReleaseError(f"Failed to branch from '{prod_stack.branch}': {r.stderr}")

        commit_message = (
            f"release: promote {source_stack.name} ({source_stack.branch}) into "
            f"{prod_stack.name} ({prod_stack.branch})\n\n"
            f"Merges the accumulated changes from `{source_stack.branch}` into a release branch\n"
            f"based on `{prod_stack.branch}`. Where conflicts existed, `{prod_stack.branch}`'s\n"
            f"version was kept (production is authoritative on conflicting lines); all\n"
            f"non-conflicting changes from `{source_stack.branch}` are included as-is.\n\n"
            f"This branch is opened as two PRs:\n"
            f"- -> {prod_stack.branch}: ships the release to production\n"
            f"- -> {dev_stack.branch}: keeps {dev_stack.name} in sync with what's going to prod"
        )

        r = _run(
            ["git", "merge", "--no-ff", "-X", "ours", f"origin/{source_stack.branch}", "-m", commit_message],
            clone_dir,
        )
        if r.returncode != 0:
            raise ReleaseError(
                f"Could not automatically merge '{source_stack.branch}' into a release branch from "
                f"'{prod_stack.branch}' — there's a structural conflict that couldn't be auto-resolved "
                f"(e.g. add/add or rename/delete). Resolve manually and retry:\n{r.stderr}"
            )

        r = _run(["git", "push", "origin", release_branch], clone_dir)
        if r.returncode != 0:
            raise ReleaseError(f"Failed to push release branch: {r.stderr}")

        svc = GitHubService(token=repo.token, repo_full_name=repo.repo_full_name, branch=prod_stack.branch, api_url=repo.api_url)

        try:
            prod_pr = await svc.open_branch_pr(
                head=release_branch,
                base=prod_stack.branch,
                title=f"release: {source_stack.name} → {prod_stack.name}",
                body=(
                    f"## Release: {source_stack.name} → {prod_stack.name}\n\n"
                    f"Promotes `{source_stack.branch}` into `{prod_stack.branch}`.\n\n"
                    f"Conflict policy: `{prod_stack.branch}` wins on any conflicting lines.\n\n"
                    f"---\n🤖 Generated by Canary"
                ),
            )
            dev_pr = await svc.open_branch_pr(
                head=release_branch,
                base=dev_stack.branch,
                title=f"release: sync {dev_stack.name} with {prod_stack.name} ({source_stack.name} release)",
                body=(
                    f"## Sync: keep {dev_stack.name} aligned with {prod_stack.name}\n\n"
                    f"Companion PR to the [{prod_stack.name} release]({prod_pr}) — merges the same "
                    f"release branch into `{dev_stack.branch}` so it doesn't drift from what just "
                    f"shipped to `{prod_stack.branch}`.\n\n---\n🤖 Generated by Canary"
                ),
            )
        except GitHubError as exc:
            raise ReleaseError(str(exc))

        return ReleaseResult(pr_urls=[prod_pr, dev_pr], branch=release_branch)
    finally:
        shutil.rmtree(clone_dir, ignore_errors=True)
