"""baseline

Revision ID: 1cd9d719001b
Revises: 
Create Date: 2026-07-01 21:27:48.446135
"""
from alembic import op
import sqlalchemy as sa


revision = '1cd9d719001b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_domain'), 'accounts', ['domain'], unique=True)
    op.create_table('github_repos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('repo_full_name', sa.String(length=255), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('api_url', sa.String(length=512), nullable=False),
    sa.Column('infrastructure_base_path', sa.String(length=512), nullable=False),
    sa.Column('auto_merge', sa.Boolean(), nullable=False),
    sa.Column('create_cicd', sa.Boolean(), nullable=False),
    sa.Column('skip_bootstrap', sa.Boolean(), nullable=False),
    sa.Column('skip_module_import', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_repos_account_id'), 'github_repos', ['account_id'], unique=False)
    op.create_index(op.f('ix_github_repos_project_name'), 'github_repos', ['project_name'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version_control_created', sa.Boolean(), nullable=False),
    sa.Column('cicd_created', sa.Boolean(), nullable=False),
    sa.Column('infrastructure_bootstrapped', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_account_id'), 'projects', ['account_id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_table('stacks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=63), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=False),
    sa.Column('verify_before_pr', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('sf_organization_name', sa.String(length=255), nullable=True),
    sa.Column('sf_account_name', sa.String(length=255), nullable=True),
    sa.Column('sf_user', sa.String(length=255), nullable=True),
    sa.Column('sf_authenticator', sa.String(length=50), nullable=False),
    sa.Column('sf_private_key_b64', sa.Text(), nullable=True),
    sa.Column('sf_database', sa.String(length=255), nullable=True),
    sa.Column('sf_schema', sa.String(length=255), nullable=True),
    sa.Column('sf_warehouse', sa.String(length=255), nullable=True),
    sa.Column('sf_role', sa.String(length=255), nullable=True),
    sa.Column('cloud_provider', sa.String(length=50), nullable=False),
    sa.Column('cloud_access_key_id', sa.String(length=255), nullable=True),
    sa.Column('cloud_secret_access_key', sa.Text(), nullable=True),
    sa.Column('cloud_region', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'name', name='uq_stack_account_name'),
    sa.UniqueConstraint('account_id', 'sort_order', name='uq_stack_account_sort_order')
    )
    op.create_index(op.f('ix_stacks_account_id'), 'stacks', ['account_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_account_id'), 'users', ['account_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('cicd',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('github_repo_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('bootstrapped', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['github_repo_id'], ['github_repos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cicd_account_id'), 'cicd', ['account_id'], unique=False)
    op.create_index(op.f('ix_cicd_github_repo_id'), 'cicd', ['github_repo_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('stack_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['stack_id'], ['stacks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_account_id'), 'conversations', ['account_id'], unique=False)
    op.create_index(op.f('ix_conversations_stack_id'), 'conversations', ['stack_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('stack_state_backends',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('github_repo_id', sa.String(), nullable=False),
    sa.Column('stack_id', sa.String(), nullable=False),
    sa.Column('state_bucket', sa.String(length=512), nullable=False),
    sa.Column('state_region', sa.String(length=50), nullable=False),
    sa.Column('state_lock_table', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['github_repo_id'], ['github_repos.id'], ),
    sa.ForeignKeyConstraint(['stack_id'], ['stacks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_repo_id', 'stack_id', name='uq_state_backend_repo_stack')
    )
    op.create_index(op.f('ix_stack_state_backends_account_id'), 'stack_state_backends', ['account_id'], unique=False)
    op.create_index(op.f('ix_stack_state_backends_github_repo_id'), 'stack_state_backends', ['github_repo_id'], unique=False)
    op.create_index(op.f('ix_stack_state_backends_stack_id'), 'stack_state_backends', ['stack_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_stack_state_backends_stack_id'), table_name='stack_state_backends')
    op.drop_index(op.f('ix_stack_state_backends_github_repo_id'), table_name='stack_state_backends')
    op.drop_index(op.f('ix_stack_state_backends_account_id'), table_name='stack_state_backends')
    op.drop_table('stack_state_backends')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_conversations_stack_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_account_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_cicd_github_repo_id'), table_name='cicd')
    op.drop_index(op.f('ix_cicd_account_id'), table_name='cicd')
    op.drop_table('cicd')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_account_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stacks_account_id'), table_name='stacks')
    op.drop_table('stacks')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_account_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_github_repos_project_name'), table_name='github_repos')
    op.drop_index(op.f('ix_github_repos_account_id'), table_name='github_repos')
    op.drop_table('github_repos')
    op.drop_index(op.f('ix_accounts_domain'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
