"""one project per account

Revision ID: 2b0156eda598
Revises: 7f5f3edccf27
Create Date: 2026-07-01 21:39:46.615286
"""
from alembic import op
import sqlalchemy as sa


revision = '2b0156eda598'
down_revision = '7f5f3edccf27'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_github_repo_account', 'github_repos', ['account_id'])
    op.create_unique_constraint('uq_project_account', 'projects', ['account_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_project_account', 'projects', type_='unique')
    op.drop_constraint('uq_github_repo_account', 'github_repos', type_='unique')
    # ### end Alembic commands ###
