"""add stack verify_max_attempts

Revision ID: 7f5f3edccf27
Revises: 1cd9d719001b
Create Date: 2026-07-01 21:29:45.087001
"""
from alembic import op
import sqlalchemy as sa


revision = '7f5f3edccf27'
down_revision = '1cd9d719001b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stacks', sa.Column('verify_max_attempts', sa.Integer(), nullable=False, server_default='3'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stacks', 'verify_max_attempts')
    # ### end Alembic commands ###
