"""add stack module_version

Revision ID: e32e69c1a218
Revises: cc8af64a1f36
Create Date: 2026-07-03 00:00:00.000000
"""
from alembic import op
import sqlalchemy as sa


revision = 'e32e69c1a218'
down_revision = 'cc8af64a1f36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stacks', sa.Column('module_version', sa.String(length=20), nullable=False, server_default='1.0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stacks', 'module_version')
    # ### end Alembic commands ###
